name: hires

obs types:
  # TODO, find a way to remove this section??
  adt:
    variable: obs_absolute_dynamic_topography
  sst:
    variable: sea_surface_temperature
  salt:
    variable: sea_water_salinity
  temp:
    variable: sea_water_temperature
  sss:
    variable: sea_surface_salinity

diagnostics:
- ObsValue
- ObsError  # Use EffectiveError, problem with that is the NaNs...
- OmB

filters:
- "domain_clip:19.5,-98.125:45.7,-98.125:45.7,-7.625:1.0,-7.625:1.0,-69.74:9.388,-79.126:8.43,-80.98:9.03,-82.96:11.65,-84.72"
- "range:ObsValue/{variable}:-100,100"

# the QC variable depends on what was run (hofx, var, ...)
- "rename:EffectiveQC/{variable}:qc:quiet"
- "rename:EffectiveQC0/{variable}:qc:quiet"

# find / calculate OmB
- "sub:ObsValue/{variable}:hofx/{variable}:OmB/{variable}:quiet"
- "rename:ombg/{variable}:OmB/{variable}:quiet"

bins:
- "qc:e=-0.5,0.5,999.5"  # TODO implement integer bins
- "latitude:r=0.25"
- "longitude:r=0.25"
