# description: combine all of the platforms from the same observation type into
# a single file

name: hires_all

source:
  level: l1a
  name: hires

operation:
  name: merge_plat

  ignore:
    adt:
    - coperl4
